name: CasinoFame
main: com.famecube.casinofame.CasinoFame
version: 1.0.0
api-version: 1.16
author: FameCube
commands:
  casino:
    description: CasinoFame main command
    usage: /casino
    permission: casinofame.use
  chips:
    description: CasinoFame chips shop
    usage: /chips
    aliases: [shop]
    permission: casinofame.use
permissions:
  casinofame.use:
    default: true
  casinofame.admin:
    default: op
  casinofame.reload:
    default: op
  casinofame.fairness:
    default: op
  casinofame.chips.admin:
    default: op
  casinofame.bypass.cooldown:
    default: op
